//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLedger
    {
        public int AccountLeaderId { get; set; }
        public string Location { get; set; }
        public string PartyName { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Particulars { get; set; }
        public string VchType { get; set; }
        public string VchNo { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<int> WorkshopId { get; set; }
        public Nullable<bool> IsClosing { get; set; }
        public Nullable<decimal> RunningBalance { get; set; }
        public Nullable<int> DueDays { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual WorkShop WorkShop { get; set; }
    }
}
