//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovedPartRequest
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public string PartNumber { get; set; }
        public string ApproverId { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
    
        public virtual NewPartRequest NewPartRequest { get; set; }
    }
}
