//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssuredGift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssuredGift()
        {
            this.AssuredGiftCategories = new HashSet<AssuredGiftCategory>();
        }
    
        public int AssuredGiftId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public string Target { get; set; }
        public string Point { get; set; }
        public string Reward { get; set; }
    
        public virtual Scheme Scheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssuredGiftCategory> AssuredGiftCategories { get; set; }
    }
}
