//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannerMobile
    {
        public int BannerId { get; set; }
        public string BannerImage { get; set; }
        public string BannerName { get; set; }
        public string Type { get; set; }
        public string Data { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> DistributorId { get; set; }
    
        public virtual Scheme Scheme { get; set; }
    }
}
