//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashBack()
        {
            this.CashbackRangeMixes = new HashSet<CashbackRangeMix>();
        }
    
        public int CashbackId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public Nullable<decimal> FromAmount { get; set; }
        public Nullable<decimal> ToAmount { get; set; }
        public string Benifit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashbackRangeMix> CashbackRangeMixes { get; set; }
        public virtual Scheme Scheme { get; set; }
    }
}
