//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashbackRangeMix
    {
        public int CashbackRangeMixId { get; set; }
        public Nullable<int> CashbackId { get; set; }
        public Nullable<int> CashbackRangeId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    
        public virtual CashbackRange CashbackRange { get; set; }
        public virtual CashBack CashBack { get; set; }
        public virtual Scheme Scheme { get; set; }
    }
}
