//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerBackOrder
    {
        public int CustomerOrderId { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<int> WorkshopId { get; set; }
        public string CONo { get; set; }
        public Nullable<System.DateTime> CODate { get; set; }
        public string PartyType { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public string CustomerOrderType { get; set; }
        public string OrderType { get; set; }
        public string PartStatus { get; set; }
        public string PartNum { get; set; }
        public string PartDesc { get; set; }
        public string BinLoc { get; set; }
        public string OrderedQty { get; set; }
        public string ProcessedQty { get; set; }
        public string PendingOrCancelledQty { get; set; }
        public string StockQty { get; set; }
        public string SellingPrice { get; set; }
        public string LocCode { get; set; }
        public string Order { get; set; }
        public string CBO { get; set; }
        public string StkMW { get; set; }
        public string ETA { get; set; }
        public string Inv { get; set; }
        public string Pick { get; set; }
        public string Alloc { get; set; }
        public string BO { get; set; }
        public string AO { get; set; }
        public string Action { get; set; }
        public string Remark { get; set; }
        public string PD { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual WorkShop WorkShop { get; set; }
    }
}
