//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySalesTrackerWithInvoiceData
    {
        public int DailySalesTrackerId { get; set; }
        public string Region { get; set; }
        public string DealerCode { get; set; }
        public string LocCode { get; set; }
        public string LocDesc { get; set; }
        public string PartNum { get; set; }
        public string PartDesc { get; set; }
        public string RootPartNum { get; set; }
        public string PartCategory { get; set; }
        public string Day { get; set; }
        public string PartGroup { get; set; }
        public string CalMonthYear { get; set; }
        public string ConsPartyCode { get; set; }
        public string ConsPartyName { get; set; }
        public string ConsPartyTypeDesc { get; set; }
        public string DocumentNum { get; set; }
        public string Remarks { get; set; }
        public string RetailQty { get; set; }
        public string ReturnQty { get; set; }
        public string NetRetailQty { get; set; }
        public string RetailSelling { get; set; }
        public string ReturnSelling { get; set; }
        public string NetRetailSelling { get; set; }
        public string DiscountAmount { get; set; }
        public string UserId { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string CoNo { get; set; }
        public string SalesUserId { get; set; }
    
        public virtual DailySalesTrackerWithInvoiceData DailySalesTrackerWithInvoiceData1 { get; set; }
        public virtual DailySalesTrackerWithInvoiceData DailySalesTrackerWithInvoiceData2 { get; set; }
    }
}
