//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyStock
    {
        public int StockId { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<int> OutletId { get; set; }
        public string ConsigneeCode { get; set; }
        public string DealerCode { get; set; }
        public string LocationCode { get; set; }
        public string PartCategoryCode { get; set; }
        public string PartNum { get; set; }
        public string RootPartNum { get; set; }
        public string StockQuantity { get; set; }
        public string Mrp { get; set; }
        public Nullable<int> PartQty { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual Outlet Outlet { get; set; }
    }
}
