//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultWinner
    {
        public int Id { get; set; }
        public int SchemeId { get; set; }
        public int WorkshopId { get; set; }
        public int GiftId { get; set; }
        public string CouponNumber { get; set; }
    
        public virtual GiftManagement GiftManagement { get; set; }
        public virtual WorkShop WorkShop { get; set; }
        public virtual Scheme Scheme { get; set; }
    }
}
