//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorBrand
    {
        public int Id { get; set; }
        public int DistributorId { get; set; }
        public int BrandId { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Distributor Distributor { get; set; }
    }
}
