//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralPurpose
    {
        public int ID { get; set; }
        public string Heading1 { get; set; }
        public string Heading2 { get; set; }
        public string Heading3 { get; set; }
        public string Heading4 { get; set; }
        public string Heading5 { get; set; }
        public string Heading6 { get; set; }
        public string Heading7 { get; set; }
        public string Heading8 { get; set; }
        public string Heading9 { get; set; }
        public string Heading10 { get; set; }
        public string Heading11 { get; set; }
        public Nullable<bool> ShowSecondScreen { get; set; }
        public string SecondScreenText { get; set; }
        public Nullable<bool> EnableSignupMailDelay { get; set; }
        public Nullable<int> DelayTime { get; set; }
    }
}
