//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiftManagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiftManagement()
        {
            this.GiftsCoupons = new HashSet<GiftsCoupon>();
            this.DefaultWinners = new HashSet<DefaultWinner>();
            this.GiftCategories = new HashSet<GiftCategory>();
        }
    
        public int GiftId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public string Gift { get; set; }
        public Nullable<int> Qty { get; set; }
        public string DrawOrder { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsCoupon> GiftsCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefaultWinner> DefaultWinners { get; set; }
        public virtual Scheme Scheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftCategory> GiftCategories { get; set; }
    }
}
