//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrowthPercentage
    {
        public int GrowthPercentageId { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<decimal> GrowthPercentage1 { get; set; }
        public Nullable<decimal> MinValue { get; set; }
    
        public virtual Distributor Distributor { get; set; }
    }
}
