//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelCriteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabelCriteria()
        {
            this.WorkShopLabelSchemes = new HashSet<WorkShopLabelScheme>();
        }
    
        public int CriteriaId { get; set; }
        public string LabelName { get; set; }
        public string TypeOfCriteria { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public string Condition { get; set; }
        public string Value { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public string SaleCondition { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Operator { get; set; }
    
        public virtual ProductGroup ProductGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkShopLabelScheme> WorkShopLabelSchemes { get; set; }
        public virtual Scheme Scheme { get; set; }
    }
}
