//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MgaCatalougeBanner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MgaCatalougeBanner()
        {
            this.MgaCatalougeProducts = new HashSet<MgaCatalougeProduct>();
        }
    
        public int Id { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public string ShortDescription { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MgaCatalougeProduct> MgaCatalougeProducts { get; set; }
    }
}
