//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MgaCatalougeProduct
    {
        public int Id { get; set; }
        public Nullable<int> BannerId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual MgaCatalougeBanner MgaCatalougeBanner { get; set; }
    }
}
