//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewPartRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewPartRequest()
        {
            this.ApprovedPartRequests = new HashSet<ApprovedPartRequest>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public int Status { get; set; }
        public string CarMake { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public string Modification { get; set; }
        public string Search { get; set; }
        public string PartNumAndQty { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string ImagePath { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovedPartRequest> ApprovedPartRequests { get; set; }
    }
}
