//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> OutletId { get; set; }
        public string AvailabilityType { get; set; }
        public string PartNumber { get; set; }
        public string RootPartNumber { get; set; }
        public string BrandName { get; set; }
        public string GroupName { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
        public virtual Outlet Outlet { get; set; }
    }
}
