//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTable()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<int> WorkshopID { get; set; }
        public Nullable<int> DeliveryAddressId { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public Nullable<decimal> PackingCharge { get; set; }
        public string UserID { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string DiscountCode { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> OutletId { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string RazorpayOrderId { get; set; }
        public string RazorpayPaymentId { get; set; }
        public string RazorpaySignature { get; set; }
        public string FromType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Distributor Distributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Outlet Outlet { get; set; }
        public virtual WorkShop WorkShop { get; set; }
    }
}
