//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outstanding
    {
        public int OutstandingId { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<int> WorkshopId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public string CustomerType { get; set; }
        public string SalesExecutiveOrBranchCode { get; set; }
        public string LessThan7Days { get; set; }
        public string C7To14Days { get; set; }
        public string C14To21Days { get; set; }
        public string C21To28Days { get; set; }
        public string C28To35Days { get; set; }
        public string C35To50Days { get; set; }
        public string C50To70Days { get; set; }
        public string MoreThan70Days { get; set; }
        public decimal LessThanCriticalDay { get; set; }
        public decimal MoreThanCriticalDay { get; set; }
        public Nullable<decimal> TotalOutstanding { get; set; }
        public string PendingBills { get; set; }
    
        public virtual Distributor Distributor { get; set; }
    }
}
