//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualifyCriteria
    {
        public int QualifyCriteriaId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public Nullable<decimal> AmountUpto { get; set; }
        public string Type { get; set; }
        public Nullable<int> NumberOfCoupons { get; set; }
        public string TypeValue { get; set; }
        public Nullable<bool> IsAll { get; set; }
        public Nullable<decimal> AdditionalCouponAmount { get; set; }
        public Nullable<int> AdditionalNumberOfCoupons { get; set; }
    
        public virtual Scheme Scheme { get; set; }
    }
}
