//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestPartFilter
    {
        public int Id { get; set; }
        public int DistributorId { get; set; }
        public string CarMake { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string Modification { get; set; }
        public string PartGroup { get; set; }
        public string PartNum { get; set; }
        public string RootPartNum { get; set; }
        public string PartDesc { get; set; }
    }
}
