//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scheme()
        {
            this.AssuredGifts = new HashSet<AssuredGift>();
            this.BannerMobiles = new HashSet<BannerMobile>();
            this.CashBacks = new HashSet<CashBack>();
            this.CashbackRanges = new HashSet<CashbackRange>();
            this.CashbackRangeMixes = new HashSet<CashbackRangeMix>();
            this.CategorySchemes = new HashSet<CategoryScheme>();
            this.Coupons = new HashSet<Coupon>();
            this.DefaultWinners = new HashSet<DefaultWinner>();
            this.FocusParts = new HashSet<FocusPart>();
            this.GiftManagements = new HashSet<GiftManagement>();
            this.LabelCriterias = new HashSet<LabelCriteria>();
            this.QualifyCriterias = new HashSet<QualifyCriteria>();
            this.SchemeLocations = new HashSet<SchemeLocation>();
            this.TargetGrowths = new HashSet<TargetGrowth>();
            this.TargetWorkShops = new HashSet<TargetWorkShop>();
            this.TicketOfJoys = new HashSet<TicketOfJoy>();
            this.FmsGroupSales = new HashSet<FmsGroupSale>();
        }
    
        public int SchemeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SchemeName { get; set; }
        public string Type { get; set; }
        public string SubSchemeType { get; set; }
        public Nullable<bool> CashBack { get; set; }
        public Nullable<bool> AssuredGift { get; set; }
        public Nullable<bool> LuckyDraw { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string DispersalFrequency { get; set; }
        public string SchemesType { get; set; }
        public string ThumbnailImage { get; set; }
        public string BannerImage { get; set; }
        public string PartCategory { get; set; }
        public string PartType { get; set; }
        public Nullable<System.DateTime> StartRange { get; set; }
        public Nullable<System.DateTime> EndRange { get; set; }
        public Nullable<decimal> FValue { get; set; }
        public Nullable<decimal> MValue { get; set; }
        public Nullable<decimal> SValue { get; set; }
        public string PartCreations { get; set; }
        public string BranchCode { get; set; }
        public Nullable<bool> IsAllSalesExecutiveSelected { get; set; }
        public string SalesExecutiveId { get; set; }
        public string PartyType { get; set; }
        public string CashbackCriteria { get; set; }
        public Nullable<bool> AreBothCbAgApplicable { get; set; }
        public Nullable<bool> CanTakeMoreThanOneGift { get; set; }
        public Nullable<int> MaxGiftsAllowed { get; set; }
        public string SchemeFor { get; set; }
        public string TargetWorkshopCriteria { get; set; }
        public Nullable<bool> FocusPartApplicable { get; set; }
        public string TargetCriteria { get; set; }
        public string RoInchargeId { get; set; }
        public Nullable<bool> IsAllRoInchargeSelected { get; set; }
        public Nullable<bool> IsCouponAllocated { get; set; }
        public Nullable<decimal> FocusPartTarget { get; set; }
        public string FocusPartBenifitType { get; set; }
        public string FocusPartBenifitTypeValue { get; set; }
        public string FocusPartBenifitTypeNumber { get; set; }
        public Nullable<System.DateTime> PrevYearFromDate { get; set; }
        public Nullable<System.DateTime> PrevYearToDate { get; set; }
        public Nullable<System.DateTime> PrevMonthFromDate { get; set; }
        public Nullable<System.DateTime> PrevMonthToDate { get; set; }
        public Nullable<decimal> GrowthCompPercentMinValue { get; set; }
        public Nullable<decimal> GrowthCompPercentBaseValue { get; set; }
        public bool AreBothAgLdApplicable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssuredGift> AssuredGifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BannerMobile> BannerMobiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashBack> CashBacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashbackRange> CashbackRanges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashbackRangeMix> CashbackRangeMixes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryScheme> CategorySchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupon> Coupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefaultWinner> DefaultWinners { get; set; }
        public virtual Distributor Distributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FocusPart> FocusParts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftManagement> GiftManagements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelCriteria> LabelCriterias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualifyCriteria> QualifyCriterias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchemeLocation> SchemeLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetGrowth> TargetGrowths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetWorkShop> TargetWorkShops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketOfJoy> TicketOfJoys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FmsGroupSale> FmsGroupSales { get; set; }
    }
}
