//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockColor
    {
        public int StockId { get; set; }
        public string StockType { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Color { get; set; }
        public string Tag { get; set; }
    }
}
