//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetGrowth
    {
        public int TragetGrowthId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<decimal> Max { get; set; }
        public Nullable<decimal> Growth { get; set; }
        public Nullable<decimal> MinTarget { get; set; }
    
        public virtual Scheme Scheme { get; set; }
    }
}
