//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TempOrder()
        {
            this.TempOrderDetails = new HashSet<TempOrderDetail>();
        }
    
        public int TempOrderId { get; set; }
        public string OrderNo { get; set; }
        public Nullable<int> DistributorId { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public Nullable<int> DeliveryAddressId { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string DiscountCode { get; set; }
        public Nullable<decimal> DeliveryCharge { get; set; }
        public Nullable<decimal> PackingCharge { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DeliveryAddress DeliveryAddress { get; set; }
        public virtual Distributor Distributor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempOrderDetail> TempOrderDetails { get; set; }
        public virtual WorkShop WorkShop { get; set; }
    }
}
