//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOrderDetail
    {
        public int TempOrderDetailId { get; set; }
        public Nullable<int> TempOrderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string AvailabilityType { get; set; }
        public Nullable<int> OutletId { get; set; }
    
        public virtual TempOrder TempOrder { get; set; }
        public virtual Product Product { get; set; }
        public virtual Outlet Outlet { get; set; }
    }
}
