//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketOfJoy
    {
        public int TicketId { get; set; }
        public Nullable<int> SchemeId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Type { get; set; }
        public string Value { get; set; }
        public string CouponCode { get; set; }
    
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual Scheme Scheme { get; set; }
    }
}
