//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFeature
    {
        public int Id { get; set; }
        public Nullable<int> FeatureId { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Feature { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Feature Feature1 { get; set; }
    }
}
