//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int UserDetailId { get; set; }
        public string ConsPartyCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserId { get; set; }
        public string DistributorId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> OTP { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Password { get; set; }
        public string Designations { get; set; }
        public Nullable<decimal> WalletAmount { get; set; }
        public string UserImage { get; set; }
        public Nullable<int> TempOrderId { get; set; }
        public string FcmToken { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
