//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variant()
        {
            this.ProductGroups = new HashSet<ProductGroup>();
        }
    
        public int VariantId { get; set; }
        public string Name { get; set; }
        public string Region { get; set; }
        public string ProductionYear { get; set; }
        public string Engine { get; set; }
        public string Description { get; set; }
        public string ChassisType { get; set; }
        public string VNo { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
