//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkshopCoupon
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> WorkshopId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CouponNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual WorkShop WorkShop { get; set; }
    }
}
