//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShopData
    {
        public int WorkShopId { get; set; }
        public string CustomerType { get; set; }
        public string CustomerCode { get; set; }
        public string PartyOwner1 { get; set; }
        public string CustomerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string CityCd { get; set; }
        public string City { get; set; }
        public string ResPhone { get; set; }
        public string AlternateNumber { get; set; }
        public string MobilePhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Tin { get; set; }
        public string GstinNo { get; set; }
        public string PartsDiscountCateg { get; set; }
        public string Designation { get; set; }
        public string ActiveYn { get; set; }
        public string Executive { get; set; }
        public string BranchCode { get; set; }
        public string CreditLimit { get; set; }
        public string Days { get; set; }
        public string ParentGroup { get; set; }
        public string DealerMapCD { get; set; }
        public string PartyTitle { get; set; }
        public string State { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string PanNo { get; set; }
        public string DiscountPer { get; set; }
        public string May_19 { get; set; }
        public string Jun_19 { get; set; }
        public string Jul_19 { get; set; }
        public string Avarage { get; set; }
        public string CreditDays { get; set; }
        public string ContactTitleCD { get; set; }
        public string ContactPersion { get; set; }
        public string Pjp { get; set; }
        public string SalesExecName { get; set; }
        public string SalesExecutiveROIncharge { get; set; }
        public string SalesHeadName { get; set; }
        public string SalesExecutiveROInchargeCode { get; set; }
        public string SalesHeadCode { get; set; }
        public string OMCEOCode { get; set; }
        public string SNO { get; set; }
        public string PartyOwner2 { get; set; }
        public string PaymentType { get; set; }
        public string BranchName { get; set; }
        public string SalesExecNumber { get; set; }
    }
}
