//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShopLabelScheme
    {
        public int Id { get; set; }
        public int WorkShopId { get; set; }
        public int SchemeId { get; set; }
        public Nullable<int> CriteriaId { get; set; }
    
        public virtual LabelCriteria LabelCriteria { get; set; }
        public virtual WorkShop WorkShop { get; set; }
    }
}
