//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaaz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkShop()
        {
            this.AccountLedgers = new HashSet<AccountLedger>();
            this.Coupons = new HashSet<Coupon>();
            this.CustomerBackOrders = new HashSet<CustomerBackOrder>();
            this.DefaultWinners = new HashSet<DefaultWinner>();
            this.DistributorWorkShops = new HashSet<DistributorWorkShop>();
            this.GiftsCoupons = new HashSet<GiftsCoupon>();
            this.OrderTables = new HashSet<OrderTable>();
            this.SalesExecutiveWorkshops = new HashSet<SalesExecutiveWorkshop>();
            this.TempOrders = new HashSet<TempOrder>();
            this.UserWorkshops = new HashSet<UserWorkshop>();
            this.WalletTransactions = new HashSet<WalletTransaction>();
            this.WorkshopBrands = new HashSet<WorkshopBrand>();
            this.WorkshopCoupons = new HashSet<WorkshopCoupon>();
            this.WorkShopLabelSchemes = new HashSet<WorkShopLabelScheme>();
            this.WorkshopsUsers = new HashSet<WorkshopsUser>();
            this.TargetWorkShops = new HashSet<TargetWorkShop>();
        }
    
        public int WorkShopId { get; set; }
        public string WorkShopName { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Gstin { get; set; }
        public string Pincode { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
        public string LandlineNumber { get; set; }
        public Nullable<int> CriticalOutstandingDays { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public Nullable<int> outletId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> TotalOutstanding { get; set; }
        public string BillingName { get; set; }
        public Nullable<int> YearOfEstablishment { get; set; }
        public string Type { get; set; }
        public string Make { get; set; }
        public string JobsUndertaken { get; set; }
        public string Premise { get; set; }
        public string GaraazArea { get; set; }
        public Nullable<int> TwoPostLifts { get; set; }
        public Nullable<bool> WashingBay { get; set; }
        public Nullable<bool> PaintBooth { get; set; }
        public Nullable<bool> ScanningAndToolKit { get; set; }
        public Nullable<int> TotalOwners { get; set; }
        public Nullable<int> TotalChiefMechanics { get; set; }
        public Nullable<int> TotalEmployees { get; set; }
        public Nullable<int> MonthlyVehiclesServiced { get; set; }
        public Nullable<decimal> MonthlyPartPurchase { get; set; }
        public Nullable<decimal> MonthlyConsumablesPurchase { get; set; }
        public string WorkingHours { get; set; }
        public string WeeklyOffDay { get; set; }
        public string Website { get; set; }
        public string InsuranceCompanies { get; set; }
        public Nullable<bool> IsMoreThanOneBranch { get; set; }
        public string MobileNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountLedger> AccountLedgers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupon> Coupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerBackOrder> CustomerBackOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefaultWinner> DefaultWinners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributorWorkShop> DistributorWorkShops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiftsCoupon> GiftsCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTables { get; set; }
        public virtual Outlet Outlet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesExecutiveWorkshop> SalesExecutiveWorkshops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempOrder> TempOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWorkshop> UserWorkshops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalletTransaction> WalletTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkshopBrand> WorkshopBrands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkshopCoupon> WorkshopCoupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkShopLabelScheme> WorkShopLabelSchemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkshopsUser> WorkshopsUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetWorkShop> TargetWorkShops { get; set; }
    }
}
